name: weather_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_icons: ^1.1.0
  cupertino_icons: ^1.0.5
  flutter_modular: ^5.0.3
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_secure_storage: ^6.0.0
  package_info_plus: ^1.4.3+1
  dartz: ^0.10.1
  geolocator: ^9.0.1
  intl: ^0.17.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
